// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClPJVMgegr0D9IipkAEBrGPT7oNNIOdBc',
    appId: '1:1075753955138:web:2af4fced2d98a6425be2db',
    messagingSenderId: '1075753955138',
    projectId: 'flutter-eb760',
    authDomain: 'flutter-eb760.firebaseapp.com',
    storageBucket: 'flutter-eb760.appspot.com',
    measurementId: 'G-01W4RC9LXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwcvnIr0ek32AEMvC-m-23JZqpk_M7as',
    appId: '1:1075753955138:android:a7240d70d8254be55be2db',
    messagingSenderId: '1075753955138',
    projectId: 'flutter-eb760',
    storageBucket: 'flutter-eb760.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzPKolF5O_wqXXpMkCHzjejGhZzpXksU',
    appId: '1:1075753955138:ios:927dbd315cd7ea395be2db',
    messagingSenderId: '1075753955138',
    projectId: 'flutter-eb760',
    storageBucket: 'flutter-eb760.appspot.com',
    iosBundleId: 'com.example.agendaCompartilhada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpzPKolF5O_wqXXpMkCHzjejGhZzpXksU',
    appId: '1:1075753955138:ios:927dbd315cd7ea395be2db',
    messagingSenderId: '1075753955138',
    projectId: 'flutter-eb760',
    storageBucket: 'flutter-eb760.appspot.com',
    iosBundleId: 'com.example.agendaCompartilhada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClPJVMgegr0D9IipkAEBrGPT7oNNIOdBc',
    appId: '1:1075753955138:web:0ac8506e983b41d45be2db',
    messagingSenderId: '1075753955138',
    projectId: 'flutter-eb760',
    authDomain: 'flutter-eb760.firebaseapp.com',
    storageBucket: 'flutter-eb760.appspot.com',
    measurementId: 'G-P89EX6QJR1',
  );
}
